### PR TITLE
[Fitting] Expose barycenter and add barycenterLocal

### PR DESCRIPTION
**Pull request by nmellado**
In the current version it is not clear that the barycenter is given in local coordinate system.

### Todo
- [x] changelog
- [x] double-check documentation
- [x] methods visibility (local should be for internal use only)

### CODE REVIEW

**Comment by nmellado** [comment]
This problem has been identified by @wgoadri

**Review by dcoeurjo — APPROVED** [review]
Oh I see. Not sure to see the side effects of this edit but the local/global clarification is valuable per se. 

Would that affect some estimators Leo is testing?

**Review by azaleostu — APPROVED** [review]
Seems good to me. I agree that the old `barycenter` was unclear whether it was in local or global space. I also agree that code using the old `barycenter` might break, but it should be fine since the change is documented.

**Comment by nmellado** [comment]
It is true that this is a breaking change that will lead to a major release bump (btw we might want to merge it after #143 then).
I checked all internal use. I don't think this will affect downstream code too much, as this function has been introduced recently and is probably not used that much. We will make that clear in the release notes.

**Comment by nmellado** [comment]
I updated the changelog to highlight the breaking change.

**Comment by nmellado** [comment]
Just pushed again to fix a bug when rebasing: I was using old `barycenter()` instead of new `barycenterLocal()` in the tests.

**Pull request merged**
