### PR TITLE
[fitting] Adding Wendland and Singular weight kernels

### PR DESCRIPTION
**Pull request by Carl-Delrieu**
Added Wendland and Singular weight kernels to weightKernel.h

### CODE REVIEW

**Comment by nmellado** [comment]
Thanks for the contribution, please find some comments below:

- [ ] Add link to the paper (in each class introduction), mention equation number for clarity.
To this end, add the bibtex entry (you can find it on the ACM website) here: https://github.com/poncateam/ponca/blob/1793b3b2e8b2b59ab30e4e3a3437ecb4e9a448af/doc/src/ponca.bib, and cite as in: https://github.com/poncateam/ponca/blob/1793b3b2e8b2b59ab30e4e3a3437ecb4e9a448af/Ponca/src/Fitting/gls.h#L19
- [ ] Use these functions in the test to be sure everything compile fine, and fitting still work.

**Comment by NAPondu** [comment]
Also fixed a typo in weightKernel.h which was failing GitHub checks

**Comment by nmellado** [comment]
I added the tests in the test suite. 
It passes if I disable tests of the added classes.
Please fix.

**Comment by nmellado** [comment]
Almost there, just need to fix the tests on windows.

**Pull request closed without merging**
